### PR TITLE
Update depending packages

### PR DESCRIPTION
**Pull request by ygkn**
This is so awesome template! 

I updated packages below.

```
 babel-cli                                  ^6.24.1  →  ^6.26.0
 babel-core                                 ^6.25.0  →  ^6.26.0
 babel-loader                                ^7.1.1  →   ^7.1.2
 babel-plugin-transform-object-rest-spread  ^6.23.0  →  ^6.26.0
 css-loader                                 ^0.28.4  →  ^0.28.7
 express                                    ^4.15.3  →  ^4.16.2
 node-sass                                   ^4.5.3  →   ^4.6.0
 redux                                       ^3.6.0  →   ^3.7.2
 webpack                                     ^3.3.0  →   ^3.8.1
 webpack-dev-middleware                     ^1.11.0  →  ^1.12.0
 webpack-dev-server                          ^2.6.0  →   ^2.9.4
 webpack-hot-middleware                     ^2.18.2  →  ^2.20.0
 webpack-merge                               ^4.1.0  →   ^4.1.1
 eslint-plugin-import                        ^2.2.0  →   ^2.8.0
```
And modified requirement to `redux-logger`.

Thanx :)

### CODE REVIEW

**Comment by zaki-yama** [comment]
@ygkn 
Thank you very much for giving a pull request!
I added a comment, please see it.

**Comment by ygkn** [comment]
I can't found your comment.
Would you tell me where is it?

Thanks.

**Comment by zaki-yama** [comment]
@ygkn 
I'm so sorry I haven't submitted. Can you see now?

**Comment by zaki-yama** [comment]
@ygkn Sorry I updated packages in #9 . Thank you very much anyway.

**Pull request closed without merging**
